# Generated by Django 4.0.4 on 2022-05-28 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, max_length=500)),
                ('profession', models.CharField(blank=True, max_length=128)),
                ('socialmedia', models.URLField(blank=True, max_length=500, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
